version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'austinorphan'
    labels:
      - 'dependencies'
      - 'npm'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      # Group all development dependencies together
      dev-dependencies:
        patterns:
          - '*'
        dependency-type: 'development'
        update-types:
          - 'minor'
          - 'patch'
      # Group all production dependencies together
      prod-dependencies:
        patterns:
          - '*'
        dependency-type: 'production'
        update-types:
          - 'patch'
    # Ignore certain dependencies
    ignore:
      # Don't update TypeScript automatically to avoid breaking changes
      - dependency-name: 'typescript'
        update-types: ['version-update:semver-major', 'version-update:semver-minor']
      # Don't update marked major versions automatically
      - dependency-name: 'marked'
        update-types: ['version-update:semver-major']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    reviewers:
      - 'austinorphan'
    labels:
      - 'dependencies'
      - 'github-actions'
    commit-message:
      prefix: 'ci'
      include: 'scope'
