name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Initialize viewer with '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: If applicable, add a minimal code sample to help reproduce the issue.
      render: javascript
      placeholder: |
        import { createViewer } from '@austinorphan/markdown-docs-viewer';
        
        const viewer = createViewer({
          // Your config here
        });

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of markdown-docs-viewer are you running?
      options:
        - 1.0.0
        - 0.9.x
        - 0.8.x
        - Other (please specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Microsoft Edge
        - Mobile Chrome
        - Mobile Safari
        - Other

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you running in?
      options:
        - Browser (Production)
        - Browser (Development)
        - Node.js
        - Webpack
        - Vite
        - Other bundler
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Please copy and paste any relevant console output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true